global using System.Collections.ObjectModel;
global using Application = System.Windows.Application;
global using Color = System.Windows.Media.Color;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using System.ComponentModel;
global using System.IO;
global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Windows;
global using System.Windows.Input;
global using System.Windows.Media.Imaging;
